FROM ubuntu:14.04

MAINTAINER Giacomo Vacca "giacomo.vacca@gmail.com"

ENV REFRESHED_AT 2016-01-04

RUN rm -rf /var/lib/apt/lists/* && apt-get update && apt-get -y -q install \
        make \
        gcc \
        bison \
        flex \
        libevent-dev \
        libcurl4-openssl-dev \
        && apt-get clean && rm -rf /var/lib/apt/lists/*

# Get scripts via a volume
RUN mkdir -p /root/scripts
VOLUME ["/root/scripts/"]

# Get source code via a volume
RUN mkdir -p /root/kamailio
VOLUME ["/root/kamailio/"]
WORKDIR /root/kamailio

EXPOSE 5060/UDP
